packageExtensions:
    "@parcel/node-resolver-core@*":
        dependencies:
            "@parcel/core": 2.12.0
    "@parcel/types@*":
        dependencies:
            "@parcel/core": 2.12.0
    "@parcel/fs@*":
        dependencies:
            "@parcel/core": 2.12.0
