name: CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

permissions:
    contents: read
    packages: write

jobs:
    build-and-lint:
        uses: GEWIS/actions/.github/workflows/lint-and-build-yarn.yml@v1
        with:
            node-version: '20.x'
            format: false
            lint: false
            build: true
            test: false
