name: CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build-and-lint:
        uses: GEWIS/actions/.github/workflows/lint-and-build-yarn.yml@v1
        with:
            node-version: '20.x'
            format: false
            lint: false
            build: true
            test: false

    docker-release:
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        needs: build-and-lint
        uses: GEWIS/actions/.github/workflows/docker-release.yml@v1
        with:
            projects: '["."]'
            github-registry: 'true'
            docker-registry: 'ghcr.io'
            docker-path: 'justsamuel/dispuutivv'
            version: 'main'

